### ISSUE TITLE
move template doc out of core, change messaging of primitive docs to encourage ECS

### ISSUE THREAD

**Issue by ngokevin** [aframevr/aframe-site#105]
- A-Frame templates should be a reference implementation rather than a core implementation. Anyone is free to use their own templating engine.
- Primitives are syntactic sugar and should be more of a reference implementation as there are many ways to do it. I'd encourage ECS a bit more. As a developer, I haven't been using them the A-Frame primitive implementation at all in my scenes.

**Comment by cvan** [comment]
> A-Frame templates should be a reference implementation rather than a core implementation. Anyone is free to use their own templating engine.

the inner definition of the `<template is="a-template">` - folks should be able to swap in any templating engine they'd like (nunjucks, handlebars, jade, swig, etc.) for that. but the actual template implementation (and the architectural improvements suggested by @dmarcos to reduce `innerHTML` calls and not have to use something like Virtual DOM) is what make templates powerful. the passing in of attributes and they magically become context variables.

templates have become a bit more complicated than they needed to by trying to satisfy the use cases of "template mixins" and "element groups" and "element repeaters" and "primitives."

I'd recommend this course of action:

1. replace all existing "templates wrapping single entities" (HTML template definitions) with "primitives" (extended JS `<a-entity>`s).
   - I [created a WIP implementation](https://github.com/cvan/aframe/blob/primitives/elements/primitives/a-cube.js) of these a few weeks ago, and @jcarpenter helped flesh out a bunch of them. you define an `attribute` -> `component.property` mapping, and for each _attribute_ you can add a transformer (function) if you need to do conditional logic and so forth.
2. rewrite the interpolation (replacement/updating) logic of templates so it's more performant (i.e., we don't do `innerHTML` on the original template fragment when variables that are passed as attributes change). again, @dmarcos had some ideas here about how to _mark_ the attributes they apply to.
3. enable swappable templating (context variables would be the ones passed as variables, as things are today; in Polymer's now-deprecated `<polymer-element>` they made you whitelist which attributes were variables - could do something like that to reduce confusion between "component" attributes.
4. promote the use of sharable templates via vulcanized HTML imports (i.e., write in HTML, build step converts them to HTML so we don't have to require browser to support HTML imports or rely on polyfills that come with limitations [i.e., CORS]).

> Primitives are syntactic sugar and should be more of a reference implementation as there are many ways to do it. I'd encourage ECS a bit more. As a developer, I haven't been using them the A-Frame primitive implementation at all in my scenes.

all of the scenes I've seen folks build since Wednesday have been of primitives and primitives only. ECS is an extensible system and will continue to drive A-Frame, but we cannot downplay the accessibility and ease of use + readability + interaction. [this tweet](https://twitter.com/enjalot/status/677931510863781888) keeps standing out in mind, and it matches the sentiment I've been sensing the past couple days.

**Comment by ngokevin** [comment]
Okay, thanks for the response. I think I can understand and envision that for now. I have some small worries, but I think they can at least be hashed out.

**Comment by dmarcos** [comment]
People are building examples based of templates is because is we're telling to do so based on the examples we provide. Primitives trade the short term and marketing impact for the long term growth and scalability of our proposal. Readability and conciseness is already covered by mixins and single object templates are redundant, less powerful and break the assumptions that components make. A bounding box component or a custom shader for instance won't work with an ```a-cube``` because they will affect to a proxy element instead of the real geometry and materials. Templates should be clearly convey that you're dealing with a group of entities to be treated as a black box. Primitives are just aliases of entities and seat in a confusing middle ground.

Our examples now feel like HTML pre CSS where the structure and style of the document are intermingled and you have to style each element individually. Resulting in more verbosity when you go beyond toy examples. We could provide an aframe-bootstrap that gives you conciseness out of the box: ```<a-entity mixin="cube"></a-entity>``` without increasing the API surface, risk for confusion and having to maintain a lot of extra code.

We should first focus on the E/C as the foundation and validate it as a sound architecture. Which is still unproven. The focus market should be just Web Developers with no computer graphics knowledge (we can grow our audience over time). I'm confident that a DOM based E/C can be presented to them in a way that it's very easy to grasp. It maps naturally to existing practices:
1. ```<a-entity>``` is your building block as analog to ```<div>``` elements. 
2. You style and customize those building blocks by adding/configuring components on the elements and you can separate that styling from your markup via mixins. Similarly as you do with CSS.

Providing low level primitives that are efficient and extensible aligns with the https://extensiblewebmanifesto.org and make our solution play better with existing template engines and frameworks that people love (react, angular...)

We're already exploring solutions that will appeal to a non pure web developers audience: SCENE inspector and VR editor. Those tools will provide higher level of abstractions that don't mix or leak into lower levels.

We should keep our scope and audience as tight as we can so we can focus. The worse thing it can happen is that we have something that nobody really identifies with. It's still too complicated for non developers and simplistic for an audience experienced on web app development. 

I would pretty much prefer to make a small audience really love ```a-frame``` rather than having lots of people mildly interested.

**Comment by ngokevin** [comment]
Random thoughts:

Hmm, the mantra is that we should have a narrow target audience. But I think this has wide appeal, and we have the resources to target everything. If we tried to focus, then everyone would have to work on the same thing. Working in pairs has worked out decently (me and you on core, cvan and josh on the in-between, casey and fernando on the UI). And we don't have to choose between depth and breadth, we're getting both at the moment.

I think as long as we realize what primitives are, aliases to ease people in, and code-wise have it on a separate layer, it's an okay compromise. With messaging and adding more libraries/modules to show it off, we'll be able to steer more advanced developers into the ECS. As long as we aren't forcing people to use primitives, let's let it slide for now as they're already in the wild. I've had as much hesitation as you've had, but let's focus our energy on things like fixing core issues and rearchitecturing the repositories.

**Comment by cvan** [comment]
:+1: ^ @ngokevin, well put
