### ISSUE TITLE
Mirror version-less docs URL from current release version URL

### ISSUE THREAD

**Issue by darkwing** [aframevr/aframe-site#334]
Right now the docs URL on the website goes to:

```
/docs/0.3.0/introduction/
```

We should provided a version-less URL which provides docs for the current version of A-Frame.  I've gotten multiple reports that someone hits the docs via Google and unknowingly got a `0.2.0` link and their 0.3.0 code doesn't work.

**Comment by cvan** [comment]
Thanks for filing. Which URLs are people are hitting?

**Comment by darkwing** [comment]
Google's been serving up the `0.2.0` URLs.  Perfect example of what is happening here:

https://github.com/aframevr/aframe/issues/1866

**Comment by ngokevin** [comment]
don't think providing versionless URLs will help because Google will still index the versioned ones. The versionless ones serve as redirects to versioned ones.

I've added a old version note at top of old documentation pages. This should hopefully guide people in the right direction.

<img width="657" alt="screen shot 2016-08-31 at 11 35 59 am" src="https://cloud.githubusercontent.com/assets/674727/18115108/21b17582-6f6f-11e6-80f6-595f6e286b30.png">

**Comment by ngokevin** [comment]
Let me know if I can update the message to be more bold, or wording changes.
