### ISSUE TITLE
Add a `humans.txt` file

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#351]
For humans

**Comment by marti1125** [comment]
@cvan something like this http://humanstxt.org/ =?

**Comment by cvan** [comment]
Yep 👍

**Comment by marti1125** [comment]
what kind of information it will have? following the standard (Authors, and contributors) could be
http://humanstxt.org/Standard.html
and an example https://www.farmacia.bio/humans.txt

**Comment by cvan** [comment]
It's not in `humans.txt` format, but I'd include similar info. as in https://addons.mozilla.org/contribute.json

**Comment by amitsin6h** [comment]
want to work assign me @cvan

**Comment by dmarcos** [comment]
@amitsin6h Feel free to start working an any of the issues that are open. Assigning the issue is just a way to mark that someone is already working on it and people don't step on each other's toes. We don't have a problem right now with multiple people wanting to pick the same issues. You can fix as many bugs as you want but I would just pick one at a time (I've seen you have requested to be assigned to a bunch of them). Looking forward to seeing your PRs.

**Comment by amitsin6h** [comment]
is their any irc channel @dmarcos

**Comment by dmarcos** [comment]
@amitsin6h We have a Slack setup:

https://aframe.io/community/#slack

See you there.

**Comment by ngokevin** [comment]
Marking won't fix, we have the community page and a humans.txt file would be additional to maintain.
