### ISSUE TITLE
add section for Scene Templates (à la Examples) for A-Frame boilerplate scene templates

### ISSUE THREAD

**Issue by cvan** [aframevr/aframe-site#442]
![image](https://user-images.githubusercontent.com/203725/28137889-b2497b4e-6703-11e7-87fa-0a37057e57d1.png)

see related issue #441

**Comment by ngokevin** [comment]
I wouldn't add these to the homepage, I prefer them hosted on a standalone page. The templates I've seen so far have been fairly low bar and available from day one (360 image, model, hello world). For a set of templates to be valuable, they have to be heavily curated and have a good enough number of them to solve a variety of use cases.

From experience of trying to help people build their scenes, starter templates don't help because people will instantly get stuck when they try to do something not prescribed in the template. Since the templates are like one-liners of HTML, they will get stuck fast. I've seen this already with the 360 tour example.

**Comment by ngokevin** [comment]
These would perhaps fit in well on the Get Started page however.

**Comment by ngokevin** [comment]
wontfixing, instead use the Glitch workflow for providing numerous remixable examples rather than from a few hello, world type "boilerplates" where you need to go thru github/npm confusion

https://github.com/aframevr/aframe/blob/master/CONTRIBUTING.md#add-glitch-examples-to-documentation
