### ISSUE TITLE
Disable dependabot

### ISSUE THREAD

**Issue by dmarcos** [aframevr/aframe-site#543]
Should we disable it? Don't see it being useful at the moment

**Comment by dmarcos** [comment]
cc @vincentfretin

**Comment by vincentfretin** [comment]
You can, the hexo server is not exposed to the internet, we use it just to build static files.

**Comment by vincentfretin** [comment]
Also all the PRs was updating yarn.lock we didn't even use and we removed the file in #536 
and we didn't commit package-lock.json so actually you won't have dependabot alerts because the file is not in the repo, that's how dependabot works. I don't see package-lock.json when I `npm install` I don't know why that's weird.
So yeah first you can close all the PRs that were updating yarn.lock.

**Comment by dmarcos** [comment]
Thanks, I disabled dependabot
